package dp.grp4.orders;

public enum OrderType {
    SHOW_RECIPES,
    SHOW_INGREDIENTS,
    SHOW_HOME,
    SHOW_CONFIRM_MODAL,
    SHOW_INGREDIENT_MODAL,
    SHOW_RECIPE_MODAL,
    SHOW_RECIPE_DETAILS_MODAL,
    SHOW_FEASIBLE_RECIPES,
    SHOW_FAVORITES,
}
